const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const puppeteer = require('puppeteer');

module.exports = {
    SlashData: new SlashCommandBuilder()
    .setName('ask-zeongpt')
    .setDescription('Ask Anything To Zeon AI (Artificial Intelligence)!')
    .addStringOption(option => option.setName('prompt').setDescription('Any Prompt For The Topic You Need To Chat with AI (Artificial Intelligence)!').setRequired(true)),
    run: async (client, interaction) => {
        if (!interaction.replied) await interaction.deferReply();

        const { options } = interaction;
        const prompt = options.getString("prompt")

        await interaction.editReply(`${client.emoji.loading} | **${prompt}** - ${interaction.user.toString()} - Getting response from the ZeonGPT...`)

        try {
            const response = await generateAnswer(prompt);

            if (response.includes("There was an error getting the response from the AI! Try again later.")) {
                return await interaction.editReply(`${client.emoji.loading} | **${prompt}** - ${interaction.user.toString()} - There was an error getting the response from the AI! Try again later.`);
            }

            const embed = new EmbedBuilder()
            .setColor("Random")
            .setDescription(`\`\`\`${response.join(`\n\n\n\n`)}\`\`\``)
            .setFooter({ text: `This response is generated by an automated chatbot. It may not always be accurate. It may contain surprises as well as mistakes.`, iconURL: client.user.displayAvatarURL({ dynamic: true }) })

            await interaction.editReply({ content: `${client.emoji.tick} | **${prompt}** - Generated response as per requested by ${interaction.user}`, embeds: [embed] });
        } catch (e) {
            console.log(e)
            await interaction.editReply(`${client.emoji.loading} | **${prompt}** - ${interaction.user.toString()} - There was an error getting the response from the AI! Try again later.`);
        }
    }
}

async function generateAnswer(prompt) {
    const browser = await puppeteer.launch({
        headless: "new"
    });
    const chatpage = await browser.newPage();

    await chatpage.goto('https://zeon.zapier.app/');

    const typingArea = 'textarea[aria-label="chatbot-user-prompt"]';
    await chatpage.waitForSelector(typingArea);
    await chatpage.type(typingArea, prompt);
    await chatpage.keyboard.press('Enter');

    await chatpage.waitForSelector('[data-testid="final-bot-response"] p')

    await sleep(10000);
    var value = await chatpage.$$eval('[data-testid="final-bot-response"]', async (elements) => {
        return elements.map((element) => element.textContent)
    });

    setTimeout(async () => {
        if (value.length === 0 || value[0] === "" || value[0] === undefined || value[0] === null) {
            value.push("There was an error getting the response from the AI! Try again later.")
        }
    }, 30000);

    await browser.close();

    value.shift();

    return value;
}

async function sleep(ms) {
    let start = new Date().getTime();
    let end = start;
    while (end < start + ms) {
        end = new Date().getTime();
    }
};